
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Execute a command.
 * 
 * `query` is what the user had TYPED when they chose this command, when it
 * differs from `input`. Supplied only when a suggestion was SELECTED, so the
 * launcher can learn `query → chosen command` (see `frecency::record_latch`).
 * `None` for a directly-typed command — a query that is its own answer teaches
 * nothing.
 */
async executeCommand(input: string, confirmed: boolean | null, runInline: boolean | null, query: string | null) : Promise<Result<CommandResultDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_command", { input, confirmed, runInline, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Confirm and run the action currently awaiting confirmation (G1).
 * 
 * Executes the EXACT resolved intent captured when the pipeline first returned
 * `needs_confirmation` — it does NOT re-resolve the raw input, so the action
 * can't shift between assessment and execution (closes the confirmation TOCTOU
 * gap). Policy is still re-checked inside `run_confirmed`, so a deny/consent
 * change since the prompt is honored. A missing or expired pending is rejected.
 */
async confirmExecution() : Promise<Result<CommandResultDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_execution") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCompletions(input: string) : Promise<Result<CompletionItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_completions", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Classify a raw input string into a typed routing decision — the SINGLE source
 * of truth for "what does Enter do?". The frontend actuates the result verbatim
 * (run a command, open a panel, go to the agent/fork card, fill a correction),
 * never re-deriving command-vs-AI from its own keyword list. Local + instant
 * (reuses the pattern router, prefix index, presets, and typo suggester).
 */
async classifyInput(input: string) : Promise<Result<RouteDecision, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("classify_input", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A "Did you mean: X?" correction for a near-miss input (e.g. an app-name typo
 * "spoti" → "open Spotify"), or `None`. Called on Enter for a single unknown
 * word BEFORE falling to the AI, so a fat-fingered app name is corrected
 * instead of sent to the model. Local + instant (in-memory fuzzy match).
 * Returns the corrected command string (the `description` of the suggestion).
 */
async suggestCorrection(input: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_correction", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dynamic command catalog for the Guide — generated from the live action
 * registry, so it never goes stale as handlers are added/removed.
 */
async getCommandCatalog() : Promise<Result<CommandInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_command_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dynamic trigger list for the Guide — structural sigils + shorthand
 * colon-triggers, the latter described by their live handler (centralised with
 * the command catalog so they never drift).
 */
async getTriggerCatalog() : Promise<Result<CommandInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_trigger_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistory() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearHistory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllSettings() : Promise<Result<AllSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHideOnBlur() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hide_on_blur") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveWindowPosition(x: number, y: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_window_position", { x, y }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAiConfig() : Promise<Result<AiConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ai_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveAiConfig(aiConfig: AiConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_ai_config", { aiConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setApiKey(provider: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMaskedApiKey(provider: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_masked_api_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAiStatus() : Promise<Result<AiStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ai_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkAiHealth() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_ai_health") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Whether the CURRENTLY SELECTED model is known to accept image input.
 * 
 * `"supported"` / `"unsupported"` / `"unknown"`. Unknown means no evidence
 * either way and the caller should ALLOW the attempt — refusing on absent
 * evidence would make a newly released vision model unusable. Verdicts come
 * from provider metadata where the endpoint reports it, and otherwise from a
 * previously observed rejection (see `providers::capability`).
 */
async getModelVision() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_vision") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Actively test the configured AI provider by sending one real request through
 * it. Unlike `check_ai_health` (which pings `/models` and passes even when the
 * *model name* is wrong), this exercises the full path — endpoint, auth, AND
 * model — so a typo'd free-form model id is caught here.
 */
async testAiConnection() : Promise<Result<AiTestResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_ai_connection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOllamaModels() : Promise<Result<OllamaModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_ollama_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The curated local-model list + which are downloaded. Available even in builds
 * without the `local-ai` engine feature (download is independent of inference).
 */
async getLocalModels() : Promise<Result<LocalModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start downloading a model's weights + tokenizer. Returns IMMEDIATELY; the
 * download runs as a background task and reports via
 * `lychi://model-download-progress` (progress, then a final `done` or `error`).
 * Idempotent. The UI must show the CPU/RAM + size warning and get explicit
 * confirmation BEFORE calling this.
 */
async downloadLocalModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_local_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a downloaded model's files to reclaim disk space.
 */
async deleteLocalModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_local_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel any in-flight agent run: bump the generation (so late events drop on
 * both ends) and cancel the current token (so the stream stops at its source).
 */
async cancelAiChat() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_ai_chat") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async agentChatStart(params: AgentChatStart) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_chat_start", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a pending approval and resume the agent loop.
 */
async agentApprove(approve: boolean, generation: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_approve", { approve, generation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGeneralConfig() : Promise<Result<GeneralConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_general_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveGeneralConfig(general: GeneralConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_general_config", { general }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCommandsConfig() : Promise<Result<CommandsConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_commands_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every keyword already taken by a built-in command.
 * 
 * Serves the Settings UI so it can warn about a colliding quicklink keyword
 * while typing. The list comes from the live registry — the same source the
 * save-path check uses — so the two can never disagree. A hand-maintained copy
 * in the frontend would drift silently every time a handler is added.
 */
async getReservedKeywords() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_reserved_keywords") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Font families installed on this system, for the Settings font pickers.
 * 
 * The WebView can't answer this itself — `document.fonts` only knows faces the
 * page has loaded — so it comes from fontconfig. Runs on a blocking thread
 * because it shells out to `fc-list`, which walks the font cache and takes
 * tens of milliseconds on a system with a thousand families.
 */
async getInstalledFonts() : Promise<Result<FontFamily[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installed_fonts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveCommandsConfig(commands: CommandsConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_commands_config", { commands }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectsConfig() : Promise<Result<ProjectsConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_projects_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProjectsConfig(projects: ProjectsConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_projects_config", { projects }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPrivacyConfig() : Promise<Result<PrivacyConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_privacy_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePrivacyConfig(privacy: PrivacyConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_privacy_config", { privacy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * C6: Grant a specific privacy consent and persist it.
 * Called by the frontend when the user confirms a privacy-gated action.
 * `feature` is one of: "ip_geolocation", "public_ip"
 */
async grantPrivacyConsent(feature: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grant_privacy_consent", { feature }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getKeybindingsConfig() : Promise<Result<KeybindingsConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_keybindings_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveKeybindingsConfig(keybindings: KeybindingsConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_keybindings_config", { keybindings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartApp() : Promise<void> {
    await TAURI_INVOKE("restart_app");
},
/**
 * Change the global hotkey at runtime: unregister old, register new, persist to config.
 */
async setHotkey(hotkey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hotkey", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Grab keyboard and wait for a modifier+key combo.
 * Returns the combo string (e.g. "Super+Space") or an error.
 */
async recordHotkey() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns terminal emulators found in PATH.
 */
async getInstalledTerminals() : Promise<string[]> {
    return await TAURI_INVOKE("get_installed_terminals");
},
/**
 * Returns whether layer-shell (Wayland) is supported on this session.
 */
async getLayerShellSupported() : Promise<boolean> {
    return await TAURI_INVOKE("get_layer_shell_supported");
},
/**
 * Returns the window strategy that is currently active (what init_window chose).
 * "layer-shell" | "toplevel" | "x11"
 */
async getActiveWindowStrategy() : Promise<string> {
    return await TAURI_INVOKE("get_active_window_strategy");
},
async getHotkeyStatus() : Promise<HotkeyStatus> {
    return await TAURI_INVOKE("get_hotkey_status");
},
/**
 * Whether the app is registered to start at login (XDG autostart entry).
 * The OS entry is the source of truth — no config field involved.
 */
async getAutostartEnabled() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_autostart_enabled") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutostartEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_autostart_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a row action into the command it stands for, then run it.
 * 
 * Row actions are declarative — a row carries `{id, label, target}`, never a
 * command string. This is where that pays off: resolution happens **here**,
 * against the handler that produced the row, so the frontend can only ask for
 * verbs a handler declared and targets it can validate. Shipping commands on
 * the action instead would make the frontend a command source, and the rules
 * engine would then see something indistinguishable from typed input.
 * 
 * The resolved string goes through `execute_command` like anything the user
 * types, so risk assessment, confirmation and the denylist all still apply —
 * one execution path, not a privileged side door.
 */
async runRowAction(handler: string, id: string, target: string) : Promise<Result<CommandResultDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_row_action", { handler, id, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hide the launcher window.
 * Called from frontend instead of window.hide() to keep hide logic centralised.
 */
async hideLauncher() : Promise<void> {
    await TAURI_INVOKE("hide_launcher");
},
/**
 * Given the text after `@`, return filesystem completions.
 * 
 * - Empty or `~` → list home directory
 * - Bare name (e.g. `Do`) → filter home directory contents
 * - `/...` → absolute path
 * - Directories sort before files, max 10 results
 */
async listPathCompletions(partial: string) : Promise<Result<CompletionItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_path_completions", { partial }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fuzzy jump-to-file for the `@` reference (Claude-Code-style). Given a bare
 * query (no path separators), returns the best matches ANYWHERE under home,
 * ranked by the same tier + frecency blend the `/` search uses. Reuses the
 * warm recursive index rather than listing a single directory.
 */
async fuzzyPathCompletions(query: string) : Promise<Result<CompletionItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fuzzy_path_completions", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List subdirectories of the given path (directories only, absolute paths).
 * Used by the in-app folder picker to avoid the native GTK dialog which
 * crashes on Wayland layer-shell surfaces.
 */
async listDirectories(path: string) : Promise<Result<DirEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_directories", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect real mounted filesystems. Home directory is always first.
 */
async getMountPoints() : Promise<Result<MountPoint[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mount_points") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a file search. An empty query is a directory *listing* (fast depth-1
 * readdir, unchanged). A non-empty query is a *fuzzy search* served by the
 * persistent per-scope nucleo index — instant per keystroke, no re-walk.
 */
async startFileSearch(query: string, scope: string, searchId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_file_search", { query, scope, searchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel any in-flight file search.
 */
async cancelFileSearch() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_file_search") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Classify user-supplied file paths into chip-ready attachments (kind, mime,
 * thumbnail, and which backend pipe they'll take). The frontend calls this once
 * per attach gesture and renders the result; it never classifies files itself.
 */
async classifyFiles(paths: string[]) : Promise<Result<FileAttachment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("classify_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stage whatever the clipboard holds as attachments (the paste gesture).
 * 
 * Two shapes, in order: copied FILES (a file manager's `file://` URI list —
 * the bytes are already on disk, so we just take the paths), or copied IMAGE
 * DATA (a screenshot tool / "copy image" — no path exists, so we spill it to
 * the clipboard-images dir first and attach that). Copied text is deliberately
 * ignored: it belongs in the input box, not the attachment tray.
 * 
 * Returns chips via the SAME classifier as every other attach gesture
 * (`files::attachment`), so a pasted file and a picked file behave identically.
 */
async attachFromClipboard() : Promise<Result<FileAttachment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_from_clipboard") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get playback status from all MPRIS media players.
 * Also refreshes the player list to discover newly started/stopped players.
 */
async mediaGetStatus() : Promise<Result<TrackInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_get_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a transport control action to a specific player.
 */
async mediaControl(busName: string, action: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_control", { busName, action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a control action to all connected players (e.g. pause all).
 */
async mediaControlAll(action: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_control_all", { action }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Seek to an absolute position in the current track of a specific player.
 */
async mediaSeek(busName: string, trackId: string, positionUs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_seek", { busName, trackId, positionUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Relative seek (±seconds) within the current track — the ±10s buttons.
 */
async mediaSeekRelative(busName: string, offsetUs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_seek_relative", { busName, offsetUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle shuffle on a specific player.
 */
async mediaSetShuffle(busName: string, on: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_set_shuffle", { busName, on }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set loop mode ("None"|"Track"|"Playlist") on a specific player.
 */
async mediaSetLoop(busName: string, mode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_set_loop", { busName, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set volume (0.0–1.0) on a specific player.
 */
async mediaSetVolume(busName: string, volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_set_volume", { busName, volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh the player list (discovers new/removed players).
 */
async mediaRefresh() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("media_refresh") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a URI using the platform's native mechanism with proper
 * desktop activation (e.g. Wayland activation tokens on Linux).
 */
async openUri(uri: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_uri", { uri }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal `path` in the file manager, selected within its parent directory.
 */
async revealPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open `path` with the default application IF it exists on disk. Returns
 * `true` if the path existed and was opened, `false` if it doesn't exist (so
 * the caller can fall back to a normal search). Used for the "paste an absolute
 * path and press Enter" flow, where a real path should open directly rather
 * than be interpreted as a scoped search term.
 */
async openPath(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllNotes() : Promise<Result<AllNotes, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The single list the unified Notes UI renders: plain notes (done=None) and
 * checklist lines (done=Some) merged, newest-updated first.
 */
async getAllItems() : Promise<Result<ScratchItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_items") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle a checklist line's done state (no-op error for plain notes).
 */
async toggleItem(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete any item (note or todo) by id, whichever table it lives in.
 */
async deleteItem(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_item", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNotes() : Promise<Result<NoteItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addNote(text: string) : Promise<Result<NoteItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_note", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateNote(id: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_note", { id, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTodos() : Promise<Result<TodoItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_todos") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addTodo(text: string) : Promise<Result<TodoItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_todo", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleTodo(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_todo", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTodo(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_todo", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current version + how this copy is managed. Never hits the network, so the
 * tab can render instantly and check for updates only when asked.
 */
async updateStatus() : Promise<Result<UpdateStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ask the update endpoint whether something newer exists.
 * 
 * On a distro package this returns the status unchanged rather than checking:
 * telling a `dnf` user that 0.2.0 exists, with no way to install it from here,
 * is noise — their package manager will tell them in its own time.
 */
async checkForUpdate() : Promise<Result<UpdateStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download and install the available update, then relaunch.
 * 
 * **Takes a backup first.** An update is the single most likely moment for a
 * migration to eat data, and it is precisely when the user is not thinking
 * about backups. The snapshot is stamped with the CURRENT version, because
 * that is whose data it holds.
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBackups() : Promise<Result<BackupInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_backups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createBackup(reason: string | null) : Promise<Result<BackupInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_backup", { reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a backup by its filename (the `name` field from `list_backups`).
 * 
 * The path is rebuilt from the backups directory rather than accepted from the
 * frontend, so a crafted argument cannot make this read an arbitrary file.
 */
async restoreBackup(name: string) : Promise<Result<RestoreReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_backup", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteBackup(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_backup", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Absolute path of the backups directory, so the UI can offer "show in files".
 */
async backupsDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("backups_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The running version — the UI needs it to mark which backups are restorable.
 */
async appVersionString() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_version_string") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the machine and decide every row.
 * 
 * **Never call this from the startup preload path.** It performs a D-Bus
 * introspect plus two name lookups, and may run the user's login shell. It
 * belongs behind a tab the user opened on purpose.
 */
async getSetupChecklist() : Promise<Result<SetupChecklistDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setup_checklist") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Put `lychi` on the user's `PATH`.
 * 
 * Refuses when the command already resolves — including a hand-made
 * `/usr/local/bin/lychi` — rather than shadowing it. Returns a sentence for the
 * UI to show as-is.
 */
async installCliLink() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_cli_link") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The full `lychi doctor` report, for the copy button in About.
 * 
 * Turns "please run `lychi doctor` in a terminal and paste the output" into one
 * click — which matters because the people who most need to send it are the
 * ones whose launcher will not open.
 */
async getDiagnostics() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAliases() : Promise<Result<AliasItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_aliases") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addAlias(name: string, command: string) : Promise<Result<AliasItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_alias", { name, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAlias(name: string, command: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_alias", { name, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAlias(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_alias", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFilePreview(path: string) : Promise<Result<FilePreviewData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_preview", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimers() : Promise<Result<TimerStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReminders() : Promise<Result<ReminderItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_reminders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addReminder(text: string, dueAt: number) : Promise<Result<ReminderItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_reminder", { text, dueAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteReminder(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_reminder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSnippets() : Promise<Result<SnippetItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSnippet(name: string, body: string) : Promise<Result<SnippetItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_snippet", { name, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSnippet(id: string, name: string, body: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_snippet", { id, name, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteSnippet(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAiPresets() : Promise<Result<AiPresetItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_ai_presets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addAiPreset(keyword: string, name: string, template: string) : Promise<Result<AiPresetItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_ai_preset", { keyword, name, template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAiPreset(id: string, keyword: string, name: string, template: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_ai_preset", { id, keyword, name, template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAiPreset(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_ai_preset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPins() : Promise<Result<PinItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPin(run: string, label: string) : Promise<Result<PinItem, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_pin", { run, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removePin(run: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_pin", { run }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversations() : Promise<Result<ConversationSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversation(id: string) : Promise<Result<Conversation | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConversation(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearConversations() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_conversations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a stored conversation into the active agent session so the next message
 * continues it (recall). Primes `agent_session` + `agent_conversation_id` with
 * the stored history, and returns the full conversation for the UI to render.
 */
async loadConversation(id: string) : Promise<Result<Conversation | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getContext() : Promise<Result<EnvironmentContext | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_context") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the PRIMARY selection — the text the user has highlighted in the focused
 * window (without copying it). Returns `None` if nothing is selected. Used to
 * auto-fill AI commands: `summarize` with no typed text acts on the selection.
 * Runs `wl-paste`/`xclip` in a blocking task (process spawn).
 */
async readSelection() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_selection") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a frontend event in the backend log.
 * 
 * Never fails: a logging call that can error is a logging call that gets
 * wrapped in a try/catch and then quietly dropped.
 */
async logFrontend(entry: FrontendLog) : Promise<void> {
    await TAURI_INVOKE("log_frontend", { entry });
},
/**
 * Open the hosted sign-in page in the system browser.
 */
async firebaseSignIn() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("firebase_sign_in") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sign out: clear all Firebase tokens from keyring.
 */
async firebaseSignOut() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("firebase_sign_out") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the currently signed-in user, or None if not signed in.
 */
async firebaseGetUser() : Promise<Result<FirebaseUser | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("firebase_get_user") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch the user's cloud credit balance.
 */
async cloudGetCredits() : Promise<Result<CreditBalance, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cloud_get_credits") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Right-aligned metadata on a row.
 * 
 * A typed vocabulary rather than a pre-formatted `String`, because formatting
 * is the frontend's job: a handler computing "3 days ago" is the same mistake
 * as a handler padding columns to align them. `Relative` carries a unix
 * timestamp and the renderer phrases it, so ages read identically across
 * timers, notes, clipboard and history.
 */
export type Accessory = 
/**
 * Literal text (a version, a size already in human units).
 */
{ kind: "text"; value: string } | 
/**
 * Unix seconds, rendered relative to now ("now", "3d").
 */
{ kind: "relative"; at: number }
/**
 * Everything the caller supplies to start a turn.
 * 
 * Grouped into a struct because the flat argument list had grown to seven
 * caller-supplied values, four of them `bool`/`u64`/`String` — the shape where
 * a transposed pair of arguments still compiles and fails at runtime. Naming
 * them at the call site removes that class of mistake, and specta turns this
 * into a TypeScript object so the frontend gains the same protection.
 */
export type AgentChatStart = { system: string; user: string; 
/**
 * Start a new conversation rather than continuing the current one.
 */
fresh: boolean; 
/**
 * Expose the tool set to the model (plain chat when false).
 */
withTools: boolean; 
/**
 * Monotonic turn id; a stale stream's tokens are dropped by the frontend.
 */
generation: number; images?: string[]; 
/**
 * How the turn renders when that differs from its content (a preset that
 * folded a large payload into a chip). Persisted with the message so a
 * RECALLED conversation renders identically, keeping the sender the only
 * decider of that split. Never sent to a provider.
 */
display?: MessageDisplay | null }
export type AiConfig = { 
/**
 * AI mode: "disabled", "byo", "ollama", "local" (cloud is deferred to
 * Phase 2.3). "local" runs bundled CPU inference via Candle (feature-gated).
 */
mode: string; 
/**
 * BYO provider preset id: "openai", "anthropic", "groq", "grok",
 * "gemini", "openrouter", or "custom". Selects the default base URL +
 * wire format; it is NOT a fixed model list.
 */
provider: string; 
/**
 * Model identifier — free-form, whatever the endpoint accepts
 * (e.g. "claude-sonnet-4-5-20250929", "gpt-4o-mini", "llama-3.3-70b-versatile").
 */
model: string; 
/**
 * Override endpoint base URL for BYO. Empty = use the preset's default.
 * Lets any OpenAI-compatible endpoint (OpenRouter, local proxies, …) work.
 */
base_url: string; 
/**
 * Request/response wire format for BYO: "openai", "anthropic", "gemini".
 * Empty = infer from the preset. Grok/Groq/OpenRouter all speak "openai".
 */
wire_format: string; 
/**
 * Ollama server URL
 */
ollama_url: string; 
/**
 * Ollama model name (e.g. "mistral:latest", "llama3:8b")
 */
ollama_model: string; 
/**
 * Local model file id — the GGUF filename under `paths::models_dir()`, e.g.
 * "llama-3.2-1b-instruct-q4_k_m.gguf". Empty = no local model selected.
 */
local_model: string; 
/**
 * AI request timeout in seconds (default 8).
 */
timeout_secs: number; 
/**
 * Max tokens the model may generate per turn (default 4096). Enforced on
 * every path: the HTTP request body (`max_tokens`, both dialects) and the
 * local engine's decode-loop bound.
 */
max_tokens: number }
export type AiPresetItem = { id: string; 
/**
 * The typed shortcut that invokes this preset (e.g. "translate").
 */
keyword: string; 
/**
 * A human-friendly display name.
 */
name: string; 
/**
 * The prompt template; `{input}` is replaced with the user's text.
 */
template: string; created_at: number; updated_at: number; 
/**
 * A shipped default (`translate`, `summarize`, `rewrite`).
 * 
 * Derived from the keyword at read time rather than stored, so it cannot
 * drift from `BUILTIN_PRESETS` and needs no migration for rows written
 * before this field existed. The UI uses it to show a "Default" badge and
 * hide the edit/delete actions; the store refuses those operations
 * regardless, since presets are reachable over IPC too.
 */
is_builtin?: boolean }
export type AiStatus = { mode: string; provider: string; model: string; has_ai_router: boolean }
/**
 * Result of a live connection test — a real round-trip, not just a reachability
 * ping. `ok` means the endpoint accepted the request AND the model produced a
 * reply; `error` carries the reason (bad key, unknown model, unreachable, …)
 * so the UI can show it inline.
 */
export type AiTestResult = { ok: boolean; error: string | null }
export type AliasItem = { name: string; command: string; created_at: number; updated_at: number }
export type AllNotes = { notes: NoteItem[]; todos: TodoItem[] }
/**
 * Single-IPC batch response for all settings data the frontend needs at startup.
 */
export type AllSettings = { ai: AiConfig; general: GeneralConfig; commands: CommandsConfig; projects: ProjectsConfig; privacy: PrivacyConfig; keybindings: KeybindingsConfig; app_version: string; layer_shell_supported: boolean; active_window_strategy: string; 
/**
 * False when running on X11 without a compositor — the transparent
 * overlay renders opaque and the user should enable compositing.
 */
screen_composited: boolean }
/**
 * How an attachment reaches the model. The frontend switches on this to decide
 * which argument of `agent_chat_start` a chip feeds, so the routing rule lives
 * in core rather than being duplicated in TypeScript.
 */
export type AttachmentRoute = 
/**
 * Encoded as a base64 image block (vision). Needs a vision-capable model.
 */
"vision" | 
/**
 * Text is extracted and inlined into the prompt.
 */
"text" | 
/**
 * We can't feed this to the model — `note` explains why.
 */
"unsupported"
/**
 * A backup on disk, as listed for the UI.
 */
export type BackupInfo = { 
/**
 * Absolute path to the `.tar.gz`.
 */
path: string; 
/**
 * Bare filename, the stable id the UI passes back to restore/delete.
 */
name: string; 
/**
 * Archive size in bytes.
 */
size_bytes: number; 
/**
 * `None` when the manifest could not be read — such an archive is listed
 * (so the user can see and delete it) but must never be restored.
 */
manifest: Manifest | null }
/**
 * What a backup was taken for. Recorded in the manifest and the filename so
 * the reason survives into the UI.
 */
export type BackupKind = 
/**
 * The user asked for it.
 */
"manual" | 
/**
 * Taken automatically before something that could lose data (an upgrade,
 * a restore, a migration).
 */
"automatic"
/**
 * A short state chip on a row.
 */
export type Badge = { text: string; tone: BadgeTone }
/**
 * Semantic state for a badge. Fixed set on purpose: a failed systemd unit, a
 * failed conversion and an expired timer must look the same, which they cannot
 * if each handler picks its own colour.
 */
export type BadgeTone = "ok" | "warn" | "error" | "muted"
/**
 * One conversation turn. A `Tool`-role message carries the `tool_call_id` it
 * answers. An `Assistant` message that requested tools keeps those calls in
 * `tool_calls` so the turn round-trips to the provider on the next request
 * (Anthropic requires the `tool_use` blocks be replayed; OpenAI the
 * `tool_calls` array).
 * 
 * `content` is a list of [`ContentPart`]s (text interleaved with images).
 * Text-only turns hold a single `Text` part. The [`content_string_or_seq`] serde
 * helper deserializes either a plain JSON string (legacy persisted sessions) or
 * the block array, so history written before vision landed still loads.
 */
export type ChatMessage = { role: Role; content: ContentPart[]; 
/**
 * Set on `Role::Tool` messages — the id of the `ToolCall` this result answers.
 */
tool_call_id?: string | null; 
/**
 * Set on `Role::Assistant` messages that requested tool calls — preserved so
 * the assistant turn replays correctly on the next request. Empty otherwise.
 */
tool_calls: ToolCall[]; 
/**
 * Marks a tool result as an error so the model can react (Anthropic
 * `is_error`, OpenAI conventionally a text marker). Only meaningful on `Tool`.
 */
is_error: boolean; 
/**
 * How this turn should RENDER, when that differs from its content.
 * 
 * A preset folds a large payload out of the bubble into a collapsed chip
 * ("Summarize the following: …" + a chip holding the blob). The model still
 * receives the full `content`; this records the split the sender already
 * computed so a RECALLED conversation renders identically instead of
 * re-deriving the boundary from a flat string — which would be a second,
 * drifting decider. Purely presentational: never sent to any provider.
 */
display?: MessageDisplay | null }
/**
 * Detected content type of clipboard text.
 */
export type ClipboardContentType = 
/**
 * A URL (http/https).
 */
{ type: "Url"; value: string } | 
/**
 * An existing file or directory path on disk.
 */
{ type: "FilePath"; value: string } | 
/**
 * An IPv4 or IPv6 address.
 */
{ type: "IpAddress"; value: string } | 
/**
 * A UUID (v1–v7).
 */
{ type: "Uuid"; value: string } | 
/**
 * A git commit hash (7–40 hex chars).
 */
{ type: "GitHash"; value: string } | 
/**
 * Valid JSON.
 */
{ type: "Json" } | 
/**
 * A stack trace or error message. Carries the key error line
 * (truncated) so suggestions can offer a meaningful search query.
 */
{ type: "ErrorTrace"; value: string } | 
/**
 * Plain text with no special classification.
 */
{ type: "Plain" }
/**
 * Clipboard capture exclusions. Unlike the flags above these default to *on*:
 * a secret that reaches the history is already leaked, so the safe default is
 * to skip it and let the user opt out, not opt in.
 */
export type ClipboardPrivacyConfig = { 
/**
 * Honour the `x-kde-passwordManagerHint` / `--sensitive` marker that
 * password managers put on the selection alongside the text.
 */
respect_sensitive_hint: boolean; 
/**
 * Normalised `wm_class` values whose copies are never recorded.
 * Matched against the window that owned focus when the copy happened.
 */
excluded_apps: string[] }
/**
 * The family a command belongs to, for grouping in the Guide. Each handler
 * declares its own via `ActionHandler::category` (default `General`), so the
 * grouping is generated from the live registry and never hardcoded frontend-side.
 * Serialized as a lowercase string (`"files"`, `"ai"`, …) for the TS bindings.
 */
export type CommandCategory = 
/**
 * Files, folders, search, browse, reveal.
 */
"files" | 
/**
 * AI chat, presets, text transforms.
 */
"ai" | 
/**
 * Web search, YouTube, definitions, bangs, bookmarks.
 */
"web" | 
/**
 * Processes, windows, services, power, system info.
 */
"system" | 
/**
 * Shell, ssh, terminal, dev encoders/utilities.
 */
"developer" | 
/**
 * Media / MPRIS control.
 */
"media" | 
/**
 * Calculators, converters, generators, notes, timers, and other tools.
 */
"utilities" | 
/**
 * Uncategorised (the default).
 */
"general"
/**
 * One row in the dynamic command catalog (Guide/help). Generated from the live
 * registry so it never goes stale. See `ActionRegistry::command_catalog`.
 */
export type CommandInfo = { 
/**
 * Handler id (e.g. "open", "translate").
 */
id: string; 
/**
 * Primary keyword the user types (e.g. "open", "qr", "translate").
 */
keyword: string; 
/**
 * One-line human description from the handler.
 */
description: string; 
/**
 * The family this command belongs to (for Guide grouping).
 */
category: CommandCategory; 
/**
 * The category's human-readable section title (so the frontend needn't map).
 */
category_title: string; 
/**
 * The category's display order (lower sorts earlier).
 */
category_order: number; 
/**
 * Whether this command mutates external state (see
 * [`ActionHandler::mutates_state`]). Surfaced so the AI coordinator can
 * refuse to run two mutating tools in one turn.
 */
mutates: boolean }
/**
 * Flat wire DTO sent to the frontend. Deliberately mirrors the historical
 * field layout so the generated TS bindings and the ~19 frontend consumer sites
 * stay unchanged — the sum-type cleanup is internal to the core. The Tauri layer
 * builds this from an `ActionResult` plus the executor's envelope
 * (risk/confirmation/executed_args/routed_by).
 */
export type CommandResultDto = { success: boolean; output?: string | null; error?: string | null; duration_ms: number; routed_by?: string | null; open_url?: string | null; needs_confirmation?: string | null; 
/**
 * When the pending confirmation is a PRIVACY CONSENT prompt: the feature
 * key to persist on "Allow and remember" (`grant_privacy_consent`).
 * Typed here because the frontend used to substring-match the prompt
 * prose to recover it — rewording a sentence broke consent persistence.
 */
consent_feature?: string | null; risk_level?: RiskLevel | null; output_type?: OutputType | null; executed_args?: string | null; launch_desktop?: string | null; focus_app?: string | null; auto_open: boolean; 
/**
 * Structured rows, when the handler produced them. Typed all the way to
 * TypeScript rather than serialised into `output` — see `Output::Rows`.
 */
sections?: Section[] | null }
export type CommandsConfig = { default_search_engine: string; youtube_url: string; shell: string; 
/**
 * Default terminal emulator for `run` commands (auto-detected if empty).
 */
terminal: string; 
/**
 * Additional WM classes to recognise as terminal emulators.
 * Matched exactly (case-insensitive) — no substring matching.
 * Example: extra_terminals = ["com.my.custom.term"]
 */
extra_terminals: string[]; 
/**
 * Additional WM classes to recognise as IDEs / code editors.
 * Matched exactly (case-insensitive). Example: extra_ides = ["my-editor"]
 */
extra_ides: string[]; 
/**
 * Terminal routing: "auto" | "manual" | "off"
 * - auto: always try sending to existing terminal first
 * - manual: only route when terminal and IDE are in the same project
 * - off: always open new terminal (current behavior)
 */
terminal_routing: string; 
/**
 * User-defined search-engine shortcuts ("bangs"): keyword → URL template.
 * The query is URL-encoded and appended (or substituted for `{}` if the
 * template contains it). E.g. `gh = "https://github.com/search?q="` makes
 * `gh tokio` open a GitHub search. Fully user-extensible — the core of a
 * no-code "ecosystem". Ships with a few sensible defaults; user entries in
 * config.toml override/extend them.
 * 
 * **Superseded by [`Self::quicklinks`]**, which can also produce shell
 * commands, opened paths, and Lychi commands. Kept because it is what
 * sits in every existing user's config.toml — entries here are merged in
 * as URL quicklinks at load time (see [`crate::quicklinks::migrate`]).
 * New entries should be written as `[[commands.quicklinks]]`.
 */
search_engines: Partial<{ [key in string]: string }>; 
/**
 * User-defined parameterized commands. Each has a keyword, a `kind`
 * (url/shell/open/command) saying what its expansion IS, and a template
 * with `{named}` placeholders:
 * 
 * ```toml
 * [[commands.quicklinks]]
 * keyword  = "co"
 * name     = "Git checkout"
 * kind     = "shell"
 * template = "git checkout {branch}"
 * ```
 * 
 * `kind` is stored rather than guessed from the template, because it
 * selects which permission decider authorizes the expansion — see
 * [`crate::quicklinks`].
 */
quicklinks?: Quicklink[]; 
/**
 * Shell approval policy: the confirmation profile + user allow/deny rules.
 * Defaults to the long-standing "ask before mutating" behaviour.
 */
shell_policy?: ShellPolicyConfig }
export type CompletionItem = { label: string; icon_path: string | null; score: number; description?: string | null; 
/**
 * Provenance — why this was suggested. Set by context suggestions,
 * `None` for non-context completions (app search, emoji, etc.).
 */
reason?: string | null; 
/**
 * Base64-encoded PNG thumbnail for image clipboard entries.
 */
thumb_b64?: string | null; 
/**
 * May Enter select this row without the user arrowing to it?
 * 
 * The VERDICT of `suggestions::Suggestion::can_be_default`, carried across
 * IPC rather than recomputed. That rule is three conditions — the row's
 * `Source` (a fallback or a guard may never be the default), its `Tier`
 * (only an identity or prefix match may), and its `CompletionKind` — and
 * the ranker is the only place that knows the first two.
 * 
 * It used to be dropped at the boundary (`.map(|s| s.item)`), so the
 * frontend re-derived it from `label`/`run` with a `startsWith` check. That
 * reimplemented one of the three conditions and lost `Source` entirely,
 * which is how a guard row could become Enter's target. Same shape as the
 * bug the suggestions module documents having fixed: "the rule existed
 * twice… they disagreed, which is precisely how `dnf search firefox`
 * launched Firefox."
 * 
 * Defaults to `false` for hand-built items that never went through the
 * ranker: refusing to auto-select is the safe direction — the user's own
 * text runs instead.
 */
can_be_default?: boolean; 
/**
 * The exact command to execute when this completion is chosen, when it
 * differs from `label`. `label` is the human-facing display text (e.g.
 * "Search YouTube: cats"); `run` is what the executor receives (e.g.
 * "yt cats"). `None` means "label is the command" or "let the frontend
 * decide" (app launch → `open {label}`). The frontend always prefers
 * `run` when present — no label reverse-parsing.
 */
run?: string | null; 
/**
 * Text to insert into the input when this completion is chosen, instead of
 * executing. Used for argument-needing hints (e.g. "volume <n>" fills
 * "system volume " so the user types the value, then Enter runs it) — the
 * tab-to-complete pattern in Raycast/Alfred. Takes precedence over `run`.
 * `None` means the completion executes (via `run` or the fallback).
 */
fill?: string | null; 
/**
 * What KIND of row this is, when that changes how selecting it behaves.
 * 
 * The frontend switches on this instead of matching display text. Label
 * strings are for humans: they get reworded, translated, and truncated, and
 * routing that depends on them breaks silently when they do. A row that
 * needs special handling declares it here.
 */
kind?: CompletionKind | null; 
/**
 * This row is user-pinned to the zero state. The ⌘K panel switches its
 * action label on this (Pin ↔ Unpin); like `can_be_default` it is a
 * backend verdict carried across IPC, never re-derived from display text.
 */
pinned?: boolean }
/**
 * Rows whose selection behaviour differs from "run the command".
 * 
 * Deliberately small: most completions need no kind at all (`None` = an
 * ordinary row that runs via `run`/`fill`/`label`). Add a variant only when the
 * frontend must genuinely branch, never as a decorative tag.
 */
export type CompletionKind = 
/**
 * A "Did you mean: X?" offer. Selecting it fills the corrected command
 * (carried in `description`) rather than running the row's text, and — the
 * part that needs a flag — it must WIN over the natural-language guard: the
 * user explicitly picked a command, so Enter must not fall through to AI.
 */
"correction" | 
/**
 * A computed result (`= 42`). It's an ANSWER, not a command: selecting it
 * displays the value rather than executing anything, and it must never be
 * written back into the input as if it were runnable text.
 */
"calc" | 
/**
 * "Ask AI: …" — send the query to the agent.
 * 
 * This is a KIND rather than a `run` string because there is no `ask`
 * handler in the registry: a `run: "ask …"` row would be re-parsed by the
 * executor's pattern router, find no such trigger, and fall through to a
 * web search. Encoding the intent in the type means nothing has to recover
 * it from text. The query itself travels in `description`.
 */
"ask-ai" | 
/**
 * "Search web: …" — the other universal escape hatch, alongside `AskAi`.
 * Same reasoning: the query lives in `description`, not in a command
 * string something downstream has to parse.
 */
"search-web" | 
/**
 * A launchable application row (`open <App>`). Set ONLY where the row is
 * unambiguously an app — the app-launcher handler and the recent-apps
 * shortlist. It is NOT stamped on pins or history rows whose `run` merely
 * starts with `open ` (a pin can be `open https://…`, a history row is a
 * past command), so the presence of this kind is an honest "this is an app",
 * and the frontend keeps a string-check fallback for the ambiguous sources.
 * Drives only a display choice (the ⌘K panel's "Open / focus" label), never
 * routing — an app row still runs via its `run` string like any other.
 */
"app"
export type ContainerInfo = { id: string; name: string; image: string; status: string }
/**
 * One block of a message's content. A message is a sequence of these: prose
 * (`Text`) interleaved with `Image` attachments. Text-only messages are a single
 * `Text` part — the common case — so the string constructors below stay ergonomic.
 */
export type ContentPart = { type: "text"; text: string } | { type: "image"; source: ImageSource }
/**
 * A persisted conversation. `messages` is the full `Session` history (system +
 * user/assistant/tool turns), so recall can continue it exactly.
 * 
 * `turn_count` is stored (not derived on read) so the recall LIST can be built
 * from a summary-shaped deserialize that skips `messages` entirely — listing
 * after every agent turn used to fully parse every conversation's bodies and
 * inline base64 images. Field order matters: `messages` sits AFTER the summary
 * fields so a partial serde struct that omits it still maps the rest by name.
 */
export type Conversation = { id: string; 
/**
 * A short title for the recall list — the first user line, truncated.
 */
title: string; 
/**
 * Number of user+assistant turns. Persisted so `list`/`prune` never touch
 * `messages`. `#[serde(default)]`: rows written before this field existed
 * decode to 0, and are corrected on their next upsert.
 */
turn_count?: number; created_at: number; updated_at: number; messages: ChatMessage[] }
/**
 * A lightweight row for the recall list — no message bodies, so listing is cheap.
 */
export type ConversationSummary = { id: string; title: string; 
/**
 * Number of user+assistant turns (excludes the system prompt & tool msgs).
 */
turn_count: number; created_at: number; updated_at: number }
/**
 * Credit balance response from the cloud credits endpoint.
 */
export type CreditBalance = { balance: number; used_this_month: number; plan: string; bonus_pool: number; resets_at: string }
export type DirChild = { name: string; is_dir: boolean }
export type DirEntry = { name: string; path: string }
export type DockerContext = { containers: ContainerInfo[] }
/**
 * The complete environmental context, refreshed on each summon.
 */
export type EnvironmentContext = { active_window: WindowContext | null; cwd: string | null; 
/**
 * CWD from the most recently focused terminal (if different from `cwd`).
 * Set when an IDE has focus but a terminal was recently used.
 * Shell commands prefer this over `cwd` when available.
 */
terminal_cwd?: string | null; 
/**
 * WM class of the detected terminal emulator (from active window or stack).
 * Used to launch `run` commands in the same terminal the user already uses.
 */
terminal_class?: string | null; 
/**
 * Git state when the working directory resolves to exactly ONE repo.
 * 
 * `None` in a multi-repo workspace: there is no single answer, and
 * inventing one would let a `git commit` target the wrong repo. Where a
 * typed command should run is resolved by
 * `multi_repo::resolve_run_targets`, which enumerates repos when asked
 * rather than caching a second copy of the same fact here.
 */
git: GitContext | null; project: ProjectContext | null; docker: DockerContext | null; 
/**
 * Current hour (0-23) for time-aware suggestion ranking.
 */
hour?: number; 
/**
 * Detected clipboard content type (read on summon).
 */
clipboard?: ClipboardContentType | null; 
/**
 * Network context (WiFi SSID, VPN status).
 */
network?: NetworkContext | null; 
/**
 * Milliseconds taken to gather context.
 */
gather_ms: number; 
/**
 * Whether `terminal_cwd` is coherent with `cwd` (same git/project root).
 * False when IDE and background terminal are in different projects — prevents
 * cross-project context contamination.
 */
terminal_matches_workspace?: boolean }
/**
 * One attached file, fully classified and ready to render as a chip.
 */
export type FileAttachment = { 
/**
 * Absolute path (`~` already expanded) — what gets sent back on submit.
 */
path: string; 
/**
 * Base name, shown on the chip.
 */
name: string; kind: FileKind; mime: string; route: AttachmentRoute; 
/**
 * Size on disk, `None` if unreadable.
 */
size_bytes: number | null; 
/**
 * A tiny PNG `data:` URI preview — images only, `None` otherwise.
 */
thumbnail: string | null; 
/**
 * Why an attachment is `Unsupported`, or a caveat worth showing. `None`
 * when the file is plainly usable.
 */
note: string | null }
/**
 * A coarse classification of what a file *is*, used to route it to the right
 * action (resize/convert an image, extract an archive, analyze a document).
 * Determined by magic bytes first (`infer`), extension second (`mime_guess`).
 */
export type FileKind = "image" | 
/**
 * A rich document we extract text from (PDF, docx, …).
 */
"doc" | 
/**
 * Plain text / source code — read directly.
 */
"text" | "archive" | "other"
export type FilePreviewData = ({ kind: "Text"; content: string; language: string; truncated: boolean } | { kind: "Image"; base64: string; mime: string } | { kind: "Unsupported"; mime: string } | { kind: "Directory"; item_count: number; children: DirChild[] }) & { 
/**
 * File size in bytes (0 for directories).
 */
size_bytes: number; 
/**
 * Last modified time as seconds since Unix epoch (0 if unavailable).
 */
modified_epoch: number; 
/**
 * Full canonical path.
 */
full_path: string }
export type FirebaseUser = { uid: string; email: string }
/**
 * A font family the user can pick.
 */
export type FontFamily = { 
/**
 * The family name, exactly as it must appear in CSS (e.g. "JetBrains Mono").
 */
name: string; 
/**
 * Whether every face in this family is fixed-width. Drives which picker the
 * family appears in: a proportional font in the monospace slot would
 * misalign every column of command output.
 */
monospace: boolean }
/**
 * A log record originating in the webview.
 */
export type FrontendLog = { 
/**
 * `error` | `warn` | `info`. Anything else is logged at info.
 */
level: string; message: string; 
/**
 * JS stack trace when the source was an exception.
 */
stack: string | null }
export type GeneralConfig = { hide_on_blur: boolean; show_duration_ms: boolean; theme: string; 
/**
 * Accent color (hex, e.g. "#7c8cff"). Empty = use the theme's default
 * monochrome accent. Drives the `--accent` CSS variable. Part of the small
 * theming engine — see `src/lib/theme.ts`.
 */
accent: string; 
/**
 * The app's font family, e.g. "Inter" or "JetBrains Mono". Empty = the
 * built-in stack, which starts at `system-ui` and follows the desktop.
 * 
 * ONE font drives the whole interface. Command *output* is the deliberate
 * exception: it stays fixed-width regardless, because `git status` and
 * `ls -la` lose their columns in a proportional face. So this is a single
 * user-facing choice, not two.
 * 
 * Prepended to the CSS stack rather than replacing it, so a font that is
 * later uninstalled degrades to the same fallbacks instead of to nothing.
 */
font_family?: string; hotkey: string; window_x: number | null; window_y: number | null; 
/**
 * Which monitor to open the launcher on: "cursor" or "primary"
 */
monitor_mode: string; 
/**
 * Window strategy: "auto", "layer-shell", "toplevel", "toplevel-window", or "x11"
 */
window_strategy: string; 
/**
 * Set true once the user has seen (and dismissed) the first-run
 * onboarding hints, e.g. the Wayland hotkey banner.
 */
first_run_completed: boolean }
export type GitContext = { repo_root: string; branch: string; dirty: boolean; remote: string | null }
/**
 * Hotkey registration status, used by the frontend to guide Wayland users
 * toward a DE-bound `lychi --toggle` shortcut when the in-app hotkey
 * cannot work system-wide.
 */
export type HotkeyStatus = { registered: boolean; 
/**
 * "wayland" | "x11"
 */
session_type: string; 
/**
 * XDG_CURRENT_DESKTOP (e.g. "KDE", "GNOME"), empty if unset
 */
desktop: string; 
/**
 * True only when something actually owns the binding on our behalf (a
 * portal binding, a desktop-settings entry, or a press we observed).
 * 
 * Deliberately NOT `registered`: an X11 grab returns Ok even when the
 * window manager keeps the key, so treating registration as reliability
 * hid the failure from precisely the users hitting it.
 */
reliable: boolean; 
/**
 * True when a grab succeeded but only a keypress can prove it works — the
 * frontend asks the user to press the hotkey rather than warning them.
 */
needs_confirmation: boolean; 
/**
 * One line explaining the verdict, suitable for showing as-is.
 */
explanation: string }
/**
 * A base64-encoded image attached to a `User` turn for vision models. `data` is
 * the raw base64 (no `data:` URI prefix); `media_type` is the MIME (`image/png`,
 * `image/jpeg`, …). Each wire encoder wraps this into its dialect's image block
 * (Anthropic `source:{type:base64,…}`, OpenAI `image_url` data-URI).
 */
export type ImageSource = { media_type: string; data: string }
/**
 * Configurable keyboard shortcuts for in-app actions.
 * Uses "Modifier+Key" string format (e.g. "Ctrl+1", "Shift+Tab").
 */
export type KeybindingsConfig = { toggle_history: string; toggle_notes: string; toggle_media: string; toggle_settings: string; open_inline_url: string; submit: string; dismiss: string; tab_complete: string; tab_back: string; switch_scope: string; web_search: string; 
/**
 * Capture a `run` shell command's output inline in Lychi instead of
 * opening a terminal (terminal is the default). Shift+Enter.
 */
run_inline: string; 
/**
 * Copy the selected search result's full path to the clipboard. Ctrl+Shift+C.
 */
copy_path: string; 
/**
 * Quick screenshot: hide Lychi and capture a region. Ctrl+Shift+S.
 */
screenshot: string; 
/**
 * Open the secondary-actions panel for the selected result. Ctrl+K.
 */
action_panel: string; 
/**
 * Stage the selected file as an attachment for the next AI turn (image →
 * vision, document → inlined text). Ctrl+Shift+A.
 */
attach_file: string; 
/**
 * Approve a destructive tool call the Rules Engine paused. Ctrl+Enter.
 */
approve_action: string; 
/**
 * Reject a paused tool call. Escape.
 */
reject_action: string; 
/**
 * Quick-AI fork card: bail out to a plain web search. Ctrl+Enter —
 * deliberately the SAME binding as `web_search`, since it is the same
 * intent ("search the web for this") on a different surface.
 */
fork_web: string; 
/**
 * Quick-AI fork card: escalate the short answer into full chat. Enter.
 */
fork_chat: string }
/**
 * One offered local model, for the settings picker. Carries the warning-gate
 * info (size/RAM) so the UI can inform the user BEFORE download.
 */
export type LocalModelInfo = { id: string; label: string; description: string; size_label: string; ram_label: string; 
/**
 * Whether the model's files are already on disk.
 */
downloaded: boolean }
/**
 * What is inside an archive, written as `manifest.json` at its root.
 */
export type Manifest = { 
/**
 * Archive layout version — see [`ARCHIVE_VERSION`].
 */
archive_version: number; 
/**
 * The Lychi version that produced it.
 */
app_version: string; 
/**
 * Unix millis when it was taken.
 */
created_at: number; kind: BackupKind; 
/**
 * Free-text note ("before restore", "before upgrade to 0.2.0").
 */
reason?: string; 
/**
 * Table name → row count, so the UI can say what is in a backup without
 * unpacking it, and restore can verify it got everything.
 */
tables: ([string, number])[]; 
/**
 * Schema generation of the archived row VALUES. `0` (the serde
 * default) marks archives from before the row envelope existed — their
 * values are raw postcard, and restore must wrap them after applying, or
 * every restored row decodes as garbage. Current archives stamp
 * [`crate::db::SCHEMA_VERSION`].
 */
schema_version?: number; 
/**
 * Which optional extras are present.
 */
has_config?: boolean; has_scripts?: boolean; 
/**
 * Clipboard image PNGs. The DB rows only hold the image PATHS, so without
 * the files themselves a restore leaves dangling references — and the
 * startup orphan-GC then deletes the PNGs the restored (older) rows don't
 * mention. Archiving the dir keeps a restore round-trip lossless.
 */
has_clipboard_images?: boolean }
/**
 * The presentational split of a user turn: the instruction line shown in the
 * bubble plus the payload folded into a collapsed chip. Computed ONCE by the
 * sender (the frontend's `presetDisplay`) and persisted with the message.
 */
export type MessageDisplay = { 
/**
 * The short line the bubble shows in place of the full content.
 */
instruction: string; 
/**
 * The chip's caption (e.g. `Selected text · 1.2k`).
 */
label: string; 
/**
 * The folded-out payload, revealed when the chip is expanded.
 */
body: string }
export type MountPoint = { path: string; label: string }
/**
 * Network context snapshot.
 */
export type NetworkContext = { 
/**
 * Active WiFi SSID, if connected.
 */
ssid: string | null; 
/**
 * Whether a VPN tunnel is active (tun/wg/ppp interface detected).
 */
vpn_active: boolean }
export type NoteItem = { id: string; text: string; created_at: number; updated_at: number }
/**
 * Model info returned by Ollama's `/api/tags` endpoint.
 */
export type OllamaModelInfo = { name: string; size: number; modified_at: string }
/**
 * How the frontend should render the output.
 */
export type OutputType = 
/**
 * Shell/terminal output — render with ANSI-to-HTML, monospace `<pre>`.
 */
"terminal" | 
/**
 * Natural language text (AI answers, notes) — clean readable sans-serif.
 */
"text" | 
/**
 * CommonMark, rendered as formatted rich text.
 * 
 * Distinct from `Text`, which is prose with no structure: a model that
 * emits a numbered list, a table, `**bold**`, or a fenced code block was
 * already producing markup, and `Text` threw the structure away and
 * displayed the source characters. That is most visible on the AI surface,
 * where the agent's answers are markdown by nature.
 * 
 * Rendered with a strict sanitiser rather than raw HTML — the content is
 * model output or third-party API text, so it is untrusted by default.
 */
"markdown" | 
/**
 * Short status message (e.g. "Launched Firefox") — compact, muted.
 */
"status" | 
/**
 * Structured weather card — JSON data rendered as a rich card.
 */
"weather" | 
/**
 * Inline SVG markup (e.g. a QR code) — embedded directly, crisp and
 * scalable. Unicode-block "ASCII" QR isn't scannable in a GUI (anti-aliased
 * text blurs module edges); SVG modules stay perfectly square (research
 * 2026-07: vector is the correct format for on-screen QR).
 */
"svg"
/**
 * Which panel a bare keyword opens. Actuated by the frontend `ui` store.
 */
export type PanelKind = "settings" | "history" | "media" | "notes" | "chat-history"
/**
 * A pin as the UI sees it, in display order.
 */
export type PinItem = { 
/**
 * The exact command Enter runs (original casing).
 */
run: string; 
/**
 * Display text.
 */
label: string; 
/**
 * Explicit order — lower shows first.
 */
position: number; created_at: number }
export type PlaybackStatus = "playing" | "paused" | "stopped"
/**
 * Privacy consent flags — all default to false (C6: Privacy First).
 * Each flag records whether the user has consented to a specific network call.
 */
export type PrivacyConfig = { 
/**
 * Allow IP geolocation (weather auto-detect via freeipapi.com)
 */
allow_ip_geolocation: boolean; 
/**
 * Allow public IP lookup (sysinfo net via ifconfig.me)
 */
allow_public_ip: boolean; 
/**
 * What the clipboard monitor refuses to record.
 */
clipboard: ClipboardPrivacyConfig }
export type ProjectContext = { root: string; kind: ProjectKind; 
/**
 * Whether a `docker-compose.yml` or `compose.yml` exists in the project root.
 */
has_compose?: boolean; 
/**
 * Discovered project scripts/targets (npm scripts, Makefile targets, Justfile recipes).
 */
scripts?: ProjectScript[]; 
/**
 * Detected package manager for Node projects (npm, pnpm, yarn, bun).
 */
package_manager?: string | null; 
/**
 * Workspace/monorepo root when this project is a subpackage.
 * Set when git root ≠ project root and the subpackage is under git root.
 * Always set for observability; `workspace_scripts` only populated for proven workspaces.
 */
workspace_root?: string | null; 
/**
 * Scripts discovered at the workspace root (supplement subpackage `scripts`).
 * Only populated when git root has explicit workspace markers (pnpm-workspace.yaml,
 * package.json "workspaces", Cargo.toml [workspace], nx/turbo/lerna/rush).
 */
workspace_scripts?: ProjectScript[] }
export type ProjectKind = "Rust" | "Node" | "Python" | "Go" | "Flutter" | "Docker"
export type ProjectScript = { 
/**
 * Command runner (e.g. "npm run", "make", "just").
 */
runner: string; 
/**
 * Script/target name.
 */
name: string }
export type ProjectsConfig = { directories: string[]; 
/**
 * Extra filenames treated as strong project markers (tier 1).
 * Example: `["flake.nix", "WORKSPACE.bazel"]`
 */
extra_strong_markers: string[]; 
/**
 * Extra filenames treated as soft project markers (tier 2).
 * Soft markers only accepted when a strong marker exists in a child dir.
 * Example: `[".devcontainer"]`
 */
extra_soft_markers: string[]; 
/**
 * Pinned workspace path — overrides auto-detection when set.
 */
pinned_workspace: string | null }
/**
 * One user-defined parameterized command.
 */
export type Quicklink = { 
/**
 * The typed keyword, e.g. `gh`. Stored normalized (trimmed, lowercased)
 * because the router matches case-insensitively.
 */
keyword: string; 
/**
 * Human-readable label shown in the results row. Falls back to the
 * keyword when empty.
 */
name?: string; 
/**
 * What the expanded template is.
 */
kind?: QuicklinkKind; 
/**
 * The template, containing `{named}` and/or legacy bare `{}` placeholders.
 */
template: string }
/**
 * What an expanded quicklink template actually is — and therefore which
 * permission decider authorizes it and how its values are escaped.
 * 
 * Stored explicitly rather than inferred from the template text. See the
 * module docs for why.
 */
export type QuicklinkKind = 
/**
 * A web URL to navigate to. Values are percent-encoded.
 * Authorized by [`crate::rules::uri::authorize_uri`].
 */
"url" | 
/**
 * A shell command line. Values are shell-quoted.
 * Authorized by [`crate::rules::shell::authorize`] — on the EXPANDED
 * string, because a template can expand into something its own text never
 * showed.
 */
"shell" | 
/**
 * A filesystem path to open with the desktop's default handler.
 * Authorized by [`crate::rules::path::authorize_path`].
 */
"open" | 
/**
 * Another Lychi command, re-entering the normal router (and therefore
 * whatever gate that command already has).
 */
"command"
export type ReminderItem = { id: string; text: string; due_at: number; fired: boolean; created_at: number }
/**
 * What a restore did, for reporting back to the user.
 */
export type RestoreReport = { tables_restored: number; rows_restored: number; config_restored: boolean; scripts_restored: boolean; 
/**
 * The safety backup taken of the pre-restore state.
 */
safety_backup: string }
/**
 * Risk level for any action. Used by the Rules Engine to decide
 * whether to auto-execute, require confirmation, or deny.
 */
export type RiskLevel = "low" | "medium" | "high"
/**
 * A conversation role. Mirrors the union both wire formats share
 * (system/user/assistant/tool).
 */
export type Role = "system" | "user" | "assistant" | "tool"
/**
 * A typed routing decision for a raw input string. Actuated verbatim by the
 * frontend. The `kind` tag maps 1:1 onto the FE dispatch switch.
 */
export type RouteDecision = 
/**
 * A deterministic handler command — run verbatim through the executor.
 */
{ kind: "command"; command: string } | 
/**
 * Natural language → AI. `confident` mirrors the old `isClearQuestion`:
 * true → straight to the full agent; false → the quick-ai fork card.
 */
{ kind: "nl"; prompt: string; confident: boolean } | 
/**
 * An AI preset invocation. When `input` is empty the FE first tries the
 * PRIMARY selection (highlighted text) as `{input}`.
 */
{ kind: "preset"; template: string; input: string } | 
/**
 * A bare panel keyword (`settings`, `history`, `notes`, …). The FE actuates
 * via `ui.openPanel`; the core carries no UI knowledge, just the tag.
 */
{ kind: "panel"; name: PanelKind; sub_tab: string | null } | 
/**
 * A typo near-miss ("Did you mean: X?"). `corrected` is filled into the
 * input for a confirming second Enter — never auto-run.
 */
{ kind: "correct"; corrected: string } | 
/**
 * An AI request with no provider configured. `command` is the web fallback
 * to run; `explicit` (an `ask …`/preset ask) drives the toast wording.
 */
{ kind: "ai-disabled"; command: string; explicit: boolean }
/**
 * A single row in a `Rows` result.
 * 
 * Deliberately the same vocabulary as `CompletionItem` (title/subtitle/icon),
 * because a list of things is a list of things whether it came from a
 * suggestion pass or an execution. Two divergent row shapes would be two
 * renderers that drift.
 */
export type Row = { title: string; subtitle?: string | null; badge?: Badge | null; accessories: Accessory[]; actions: RowAction[] }
/**
 * One action a row supports, declared by the handler that produced the row.
 * 
 * **Declarative, never executable.** The handler names an `id` and the `target`
 * it applies to; it does NOT ship a command string for the frontend to run.
 * That distinction is the safety property: if actions carried commands, then
 * anything able to populate a row could propose arbitrary execution, and the
 * rules engine would see something indistinguishable from user input. Instead
 * the producing handler maps `(id, target)` back to a command — and because it
 * enumerated the rows in the first place, it can reject a `target` it never
 * emitted, which is what stops injection through the argument.
 */
export type RowAction = { 
/**
 * Verb, resolved by the producing handler (e.g. `"restart"`).
 */
id: string; 
/**
 * Human label for the ⌘K menu.
 */
label: string; 
/**
 * Which row this acts on (e.g. the unit name). Echoed back on invocation
 * and validated by the handler against what it produced.
 */
target: string; 
/**
 * Per-action risk, so `stop` can confirm while `logs` does not. Finer than
 * the handler-wide `default_risk`; the rules engine remains the gate.
 */
risk?: RiskLevel | null }
/**
 * A single item in the unified Notes surface. A plain note has `done: None`;
 * a checklist line has `done: Some(true|false)`. The two are stored in
 * separate on-disk tables (NOTES / TODOS) for backwards compatibility, but are
 * merged into this one type at the API boundary so the UI shows a single list.
 */
export type ScratchItem = { id: string; text: string; 
/**
 * None = plain note; Some = checklist line (checked/unchecked).
 */
done: boolean | null; created_at: number; updated_at: number }
/**
 * A titled group of rows. Grouping is explicit rather than implied by sort
 * order, so "failed" units can lead without a handler encoding that in a
 * string.
 */
export type Section = { title?: string | null; rows: Row[]; 
/**
 * Which handler produced these rows.
 * 
 * Row actions are resolved by their producer, so the frontend has to say
 * who that was when invoking one. It cannot be inferred from the envelope:
 * `routed_by` records HOW the command was routed ("explicit"/"pattern"/
 * "ai"), not WHO handled it. Carrying it on the section keeps the action
 * resolvable without the frontend guessing.
 */
handler: string }
export type SetupChecklistDto = { steps: SetupStepDto[]; 
/**
 * How many rows want attention. Drives the sidebar badge, which is hidden
 * entirely at zero — deliberately not an "x of y" progress count.
 */
actionable: number }
/**
 * A checklist row, flattened for the frontend.
 * 
 * `state` is a plain string rather than a tagged union because the UI switches
 * on it directly; `detail` is whatever the backend decided to say, rendered
 * verbatim. The frontend owns no copy for these — a second copy table is a
 * place for the two sides to disagree, and this is exactly the text where
 * "not applicable" turns into shaming if it drifts.
 */
export type SetupStepDto = { id: string; title: string; 
/**
 * "done" | "actionable" | "not_applicable"
 */
state: string; detail: string; 
/**
 * "open_tab" | "install_cli" | "manual", absent when there is nothing to do.
 */
action: string | null; 
/**
 * Which settings tab `open_tab` should open.
 */
tab: string | null; 
/**
 * The command `manual` should display.
 */
command: string | null }
/**
 * User-tunable shell authorization: the approval profile plus custom
 * allow/deny regex rules layered on top of the built-in policy.
 * 
 * Precedence (strongest first), mirroring Warp's model:
 * 1. built-in hard Deny (denylist / catastrophes) — absolute
 * 2. user `deny` rule — absolute for the user
 * 3. user `allow` rule — runs without asking (but never overrides 1 or 2)
 * 4. built-in Confirm/Allow under the active profile
 */
export type ShellPolicyConfig = { profile?: ShellProfile; 
/**
 * Regexes for commands the user always wants to run without confirmation.
 * Matched against the raw command string. A hard Deny still overrides.
 */
allow?: string[]; 
/**
 * Regexes for commands the user always wants blocked outright. Absolute for
 * the user — no approval prompt, like the built-in denylist.
 */
deny?: string[] }
/**
 * How aggressively the agent must ask before running a shell command.
 * 
 * A profile can only make the gate STRICTER, never weaker: a hard `Deny` (the
 * denylist, structural catastrophes, a user deny rule) is enforced in every
 * profile regardless. What the profile tunes is the boundary between "runs
 * immediately" and "asks first" for the non-denied commands.
 */
export type ShellProfile = 
/**
 * Confirm EVERY command before it runs, even a read-only `ls`. The most
 * cautious posture — nothing the agent proposes runs unattended.
 */
"strict" | 
/**
 * Confirm commands that mutate state or match a dangerous pattern;
 * read-only commands run immediately. Lychi's long-standing behaviour, and
 * the `#[default]` so every existing user's config keeps today's gate.
 */
"ask-on-write" | 
/**
 * Auto-accept: every command runs without asking EXCEPT hard-denied ones
 * (the denylist, structural catastrophes, and user deny rules — those are
 * still blocked outright). The loosest posture; a Deny can never be
 * auto-accepted. Use only when you trust the agent in this environment.
 */
"auto-accept"
export type SnippetItem = { id: string; name: string; body: string; created_at: number; updated_at: number }
/**
 * Serializable timer status sent to the frontend.
 */
export type TimerStatus = { id: string; name: string; duration_secs: number; remaining_secs: number; elapsed_secs: number; paused: boolean; done: boolean; stopwatch: boolean }
export type TodoItem = { id: string; text: string; done: boolean }
/**
 * A tool invocation the model requested. `id` correlates the eventual
 * `ChatMessage::tool_result`. `args` is the single string argument (the
 * provider decodes its wire-specific `{"args": ...}` object into this).
 */
export type ToolCall = { id: string; name: string; args: string }
/**
 * Current playback state from a media player via MPRIS.
 */
export type TrackInfo = { title: string; artist: string; album: string; art_url: string | null; 
/**
 * MPRIS track object path (needed for SetPosition).
 */
track_id: string; 
/**
 * Track length in microseconds.
 */
length_us: number; 
/**
 * Current playback position in microseconds.
 */
position_us: number; status: PlaybackStatus; 
/**
 * D-Bus bus name (e.g. "org.mpris.MediaPlayer2.spotify").
 */
bus_name: string; 
/**
 * Friendly player name (e.g. "Spotify", "Firefox").
 */
player_name: string; 
/**
 * Whether the player supports next/previous/seek — the UI hides a control
 * the active player can't honour rather than showing a dead button. All
 * optional in MPRIS, so missing properties default to false/None.
 */
can_go_next: boolean; can_go_previous: boolean; can_seek: boolean; 
/**
 * Shuffle state, `None` if the player doesn't expose the `Shuffle` property.
 */
shuffle: boolean | null; 
/**
 * Loop mode, `None` if unsupported; otherwise "None" | "Track" | "Playlist".
 */
loop_status: string | null; 
/**
 * Volume 0.0–1.0, `None` if the player doesn't expose `Volume`.
 */
volume: number | null }
/**
 * What the Settings tab needs to say about updates, in one round trip.
 */
export type UpdateStatus = { 
/**
 * Running version.
 */
current_version: string; 
/**
 * How this copy was installed (`appimage` / `flatpak` / `system`).
 */
install_kind: string; 
/**
 * Whether Lychi may update itself here. False for distro packages.
 */
can_self_update: boolean; 
/**
 * What to tell the user when it cannot — the command they'd actually run.
 */
hint: string; 
/**
 * Newer version available, if a check has found one.
 */
available_version: string | null; 
/**
 * Release notes for that version.
 */
notes: string | null; 
/**
 * Set when a check could not complete (offline, no endpoint configured).
 */
error: string | null }
export type WindowContext = { title: string; wm_class: string; pid: number; is_terminal: boolean; is_ide?: boolean; 
/**
 * Stable per-window identifier. On KWin: UUID string from `w.internalId`.
 * On X11: hex-formatted X11 window ID (e.g. `"0x00a00012"`).
 * `None` when unavailable (older Plasma, headless, etc.).
 */
window_id?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
