pub mod app_launcher;
pub mod ask;
pub mod browse;
pub mod calc;
pub mod file_open;
pub mod icons;
#[cfg(feature = "mpris")]
pub mod media;
pub mod notes;
pub mod project_open;
pub mod shell_exec;
pub mod sysinfo;
pub mod system;
pub mod url_open;
pub mod weather;
pub mod weather_ask;
pub mod web_search;
pub mod youtube;
