use std::sync::Arc;
use std::time::Instant;

use async_trait::async_trait;
use redb::Database;

use crate::action_registry::grammar::{ArgKind, Grammar, Operand, ToolGroup, Verb};
use crate::action_registry::{
    ActionHandler, ActionResult, BadgeTone, CommandCategory, CompletionItem, ExecContext, Output,
    OutputType, RiskLevel, Row, Section,
};
use crate::error::LychiError;
use crate::notes::store::{MAX_NOTES, NotesStore};

// ---- Notes handler ----

const NOTE_SUBCOMMANDS: &[(&str, &str)] = &[
    ("read", "List all saved notes"),
    ("delete", "Delete a note by ID (e.g. note delete abc)"),
];

/// Whether `s` is a store-generated item id.
///
/// Note and todo ids come from `db::new_id()` — a UUIDv7 — so unlike snippet
/// names (user-authored free text) this can be validated strictly. Anything
/// that is not a well-formed UUID did not come from the store, so it cannot
/// name a real row and is refused rather than passed to a lookup.
fn is_valid_item_id(s: &str) -> bool {
    uuid::Uuid::parse_str(s).is_ok()
}

/// Resolve a note row action into the command it stands for.
pub fn resolve_note_action(id: &str, target: &str) -> Result<String, String> {
    if id != "delete" {
        return Err(format!("Unknown note action '{id}'"));
    }
    if !is_valid_item_id(target) {
        return Err(format!("Invalid note id '{target}'"));
    }
    Ok(format!("note delete {target}"))
}

/// Resolve a todo row action into the command it stands for.
///
/// `toggle` maps to the `done` verb because the store operation IS a toggle —
/// there is no separate un-done path, and pretending otherwise in the action id
/// would invent a distinction the backend does not have.
pub fn resolve_todo_action(id: &str, target: &str) -> Result<String, String> {
    let verb = match id {
        "toggle" => "done",
        "delete" => "delete",
        other => return Err(format!("Unknown todo action '{other}'")),
    };
    if !is_valid_item_id(target) {
        return Err(format!("Invalid todo id '{target}'"));
    }
    Ok(format!("todo {verb} {target}"))
}

/// `note`'s argument surface. Historically the flat `add` form was BARE text
/// (any non-subcommand input became a note), which `to_flat`'s verb-prefix rule
/// cannot render from a multi-verb grammar — so the parser learned the explicit
/// `add <text>` verb instead (see `execute`), the bare-text fallthrough staying
/// for humans. The JSON Schema and the structured→flat adapter both derive
/// from this; the drift test proves the parser accepts each verb's rendering.
const NOTE_GRAMMAR: Grammar = Grammar {
    verbs: &[
        Verb {
            name: "add",
            desc: "Save a new note. The first line becomes its title. At most \
                   5 notes are kept.",
            mutates: true,
            operands: &[Operand {
                name: "text",
                desc: "The note text to save. May span multiple lines; the \
                       first line becomes the note's title.",
                required: true,
                kind: ArgKind::Text,
                prefix: None,
            }],
        },
        Verb {
            name: "read",
            desc: "List all saved notes.",
            mutates: false,
            operands: &[],
        },
        Verb {
            name: "delete",
            desc: "Delete one note by its id.",
            mutates: true,
            operands: &[Operand {
                name: "id",
                desc: "The note's id — a UUID generated by the store when the \
                       note was added.",
                required: true,
                kind: ArgKind::Text,
                prefix: None,
            }],
        },
    ],
};

/// Normalize the tool's `args` to the flat string the parser understands:
/// `"add <text>"`, `"read"`, or `"delete <id>"`. A constrained model sends the
/// structured JSON (`{"action":"add","text":"buy milk"}`); a human or
/// legacy/flat caller sends the string directly (bare text still adds via the
/// fallthrough), and malformed JSON falls back to the raw string. Keeps
/// `execute` on `&str`.
fn note_args_to_flat(args: &str) -> String {
    NOTE_GRAMMAR
        .flatten_json(args)
        .unwrap_or_else(|| args.trim().to_string())
}

pub struct NotesHandler {
    db: Arc<Database>,
}

impl NotesHandler {
    pub fn new(db: Arc<Database>) -> Self {
        Self { db }
    }

    /// Format a note's first line as its title (truncated to ~40 bytes on a
    /// char boundary — a naive `[..40]` panics when byte 40 splits a multi-byte
    /// UTF-8 char, e.g. an emoji or CJK glyph in the note).
    fn note_title(text: &str) -> &str {
        let first_line = text.lines().next().unwrap_or(text);
        if first_line.len() > 40 {
            let mut end = 40;
            while end > 0 && !first_line.is_char_boundary(end) {
                end -= 1;
            }
            &first_line[..end]
        } else {
            first_line
        }
    }
}

#[async_trait]
impl ActionHandler for NotesHandler {
    fn triggers(&self) -> &'static [crate::action_registry::Trigger] {
        use crate::action_registry::Trigger;
        static TRIGGERS: &[Trigger] = &[Trigger::keywords(&["note", "notes"])];
        TRIGGERS
    }

    fn id(&self) -> &str {
        "note"
    }

    fn description(&self) -> &str {
        "Notes — add, list, or delete notes. Usage: note <text> to add, note read to list, note delete <id> to remove"
    }
    fn usage(&self) -> &str {
        "text to add a note, 'read' to view all, 'delete <id>' to remove. Max 5 notes"
    }
    fn grammar(&self) -> Option<Grammar> {
        Some(NOTE_GRAMMAR)
    }
    fn tool_group(&self) -> ToolGroup {
        ToolGroup::Personal
    }
    fn category(&self) -> CommandCategory {
        CommandCategory::Utilities
    }

    async fn execute(&self, _ctx: &ExecContext, args: &str) -> Result<ActionResult, LychiError> {
        let start = Instant::now();
        // A constrained model sends `{"action":..,"text":..}`; flatten it (and a
        // plain-string caller passes through) to the form the parser reads.
        let flat = note_args_to_flat(args);
        let text = flat.trim();
        let store = NotesStore::new();

        // No args → open notes panel. A bare `add` (the grammar's rendering of
        // an empty text, and `note add` typed by a human) means the same thing:
        // there is nothing to save yet, so open the panel to write in.
        if text.is_empty() || text == "add" {
            return Ok(
                ActionResult::ok("__notes_panel__".to_string(), OutputType::Status)
                    .with_duration(start.elapsed().as_millis() as u64),
            );
        }

        // Explicit `add <text>` verb — the grammar's flat rendering (a
        // multi-verb grammar must render a verb; bare text can't carry one).
        // Everything after `add ` is the note text VERBATIM, so `note add read`
        // saves "read" instead of listing. The bare-text fallthrough below
        // stays for humans; the one behavior change is that a typed note can no
        // longer START with the word "add" — the verb wins.
        let (text, explicit_add) = match text.strip_prefix("add ") {
            Some(rest) if !rest.trim().is_empty() => (rest.trim(), true),
            _ => (text, false),
        };

        // "read" / "list" → list all notes
        if !explicit_add && (text.eq_ignore_ascii_case("read") || text.eq_ignore_ascii_case("list"))
        {
            let notes = store.get_notes(&self.db)?;
            if notes.is_empty() {
                return Ok(
                    ActionResult::ok("No notes saved".to_string(), OutputType::Text)
                        .with_duration(start.elapsed().as_millis() as u64),
                );
            }
            // The id was being printed as visible text purely so the user could
            // retype it into `note delete <id>`. A row carries it invisibly as
            // the action target, so the id leaves the display entirely and the
            // age it never showed takes that space instead.
            let rows: Vec<Row> = notes
                .iter()
                .map(|n| {
                    Row::new(Self::note_title(&n.text))
                        .accessory_at(n.updated_at as i64)
                        .action("delete", "Delete", &n.id, Some(RiskLevel::Medium))
                })
                .collect();
            return Ok(ActionResult {
                success: true,
                output: Output::Rows {
                    sections: vec![Section {
                        title: Some(format!("Notes ({}/{})", rows.len(), MAX_NOTES)),
                        rows,
                        handler: "notes".to_string(),
                    }],
                },
                duration_ms: start.elapsed().as_millis() as u64,
                ..Default::default()
            });
        }

        // "delete <id>" → delete a note
        if let Some(rest) = (!explicit_add)
            .then(|| {
                text.strip_prefix("delete ")
                    .or_else(|| text.strip_prefix("del "))
                    .or_else(|| text.strip_prefix("rm "))
            })
            .flatten()
        {
            let id = rest.trim();
            store.delete_note(&self.db, id)?;
            return Ok(
                ActionResult::ok(format!("Note deleted: {id}"), OutputType::Status)
                    .with_duration(start.elapsed().as_millis() as u64),
            );
        }

        // Add a new note
        match store.add_note(&self.db, text) {
            Ok(item) => Ok(ActionResult::ok(
                format!(
                    "Note saved ({} chars, {}/{})",
                    item.text.len(),
                    store.notes_count(&self.db)?,
                    MAX_NOTES
                ),
                OutputType::Status,
            )
            .with_duration(start.elapsed().as_millis() as u64)),
            Err(e) if e.to_string().contains("limit reached") => {
                // Return sentinel so frontend opens NotesPanel with pending note
                Ok(
                    ActionResult::ok(format!("__notes_limit__:{text}"), OutputType::Status)
                        .with_duration(start.elapsed().as_millis() as u64),
                )
            }
            Err(e) => Err(e),
        }
    }

    async fn completions(&self, partial: &str) -> Vec<CompletionItem> {
        let lower = partial.to_lowercase();
        NOTE_SUBCOMMANDS
            .iter()
            .filter(|(cmd, _)| cmd.contains(&lower) || lower.is_empty())
            .map(|(cmd, desc)| CompletionItem {
                label: cmd.to_string(),
                icon_path: None,
                score: if cmd.starts_with(&lower) { 100 } else { 50 },
                description: Some(desc.to_string()),
                reason: None,
                thumb_b64: None,
                run: Some(format!("note {cmd}")),
                ..Default::default()
            })
            .collect()
    }
}

// ---- Todo handler ----

pub struct TodoHandler {
    db: Arc<Database>,
}

impl TodoHandler {
    pub fn new(db: Arc<Database>) -> Self {
        Self { db }
    }
}

const TODO_SUBCOMMANDS: &[(&str, &str)] = &[
    ("add", "Add a todo item (e.g. todo add buy milk)"),
    ("list", "List all todo items"),
    ("done", "Mark a todo as done by ID"),
    ("delete", "Delete a todo by ID"),
    ("summary", "Show notes and todos summary"),
];

/// The todo id operand `done`/`delete` share.
const TODO_ID: Operand = Operand {
    name: "id",
    desc: "The todo's id — a UUID, shown in the confirmation when the item was \
           added.",
    required: true,
    kind: ArgKind::Text,
    prefix: None,
};

/// `todo`'s argument surface: the verbs `execute`'s match dispatches on
/// (canonical spellings only; the parser's extra aliases like `ls`/`check`/`rm`
/// stay accepted on the flat path). The JSON Schema and the structured→flat
/// adapter both derive from this.
const TODO_GRAMMAR: Grammar = Grammar {
    verbs: &[
        Verb {
            name: "add",
            desc: "Add a new todo item.",
            mutates: true,
            operands: &[Operand {
                name: "text",
                desc: "The todo text (e.g. \"buy milk\").",
                required: true,
                kind: ArgKind::Text,
                prefix: None,
            }],
        },
        Verb {
            name: "list",
            desc: "List all todo items with their done/pending state.",
            mutates: false,
            operands: &[],
        },
        Verb {
            name: "done",
            desc: "Toggle a todo's done state by id — calling it again marks \
                   the item undone (the store operation IS a toggle).",
            mutates: true,
            operands: &[TODO_ID],
        },
        Verb {
            name: "delete",
            desc: "Delete a todo item by id.",
            mutates: true,
            operands: &[TODO_ID],
        },
        Verb {
            name: "summary",
            desc: "Show a combined text summary of all notes and todos.",
            mutates: false,
            operands: &[],
        },
    ],
};

/// Normalize the tool's `args` to the flat `"<verb> [<operand>]"` string the
/// parser already understands. A constrained model sends the structured JSON
/// (`{"action":"add","text":"buy milk"}`); a human or legacy/flat caller sends
/// the string directly, and malformed JSON falls back to the raw string (a
/// bare verb missing its operand gets the parser's own usage error, which is
/// the right message). Keeps `execute` on `&str`.
fn todo_args_to_flat(args: &str) -> String {
    TODO_GRAMMAR
        .flatten_json(args)
        .unwrap_or_else(|| args.trim().to_string())
}

#[async_trait]
impl ActionHandler for TodoHandler {
    fn triggers(&self) -> &'static [crate::action_registry::Trigger] {
        use crate::action_registry::Trigger;
        static TRIGGERS: &[Trigger] = &[Trigger::keywords(&["todo", "todos"])];
        TRIGGERS
    }

    fn id(&self) -> &str {
        "todo"
    }

    fn description(&self) -> &str {
        "Todo list — add, list, check off, or delete items. Usage: todo add <text>, todo list, todo done <id>, todo delete <id>"
    }
    fn usage(&self) -> &str {
        "'add <text>', 'list', 'done <id>', 'delete <id>', 'summary'"
    }
    fn grammar(&self) -> Option<Grammar> {
        Some(TODO_GRAMMAR)
    }
    fn tool_group(&self) -> ToolGroup {
        ToolGroup::Personal
    }
    fn category(&self) -> CommandCategory {
        CommandCategory::Utilities
    }

    async fn execute(&self, _ctx: &ExecContext, args: &str) -> Result<ActionResult, LychiError> {
        let start = Instant::now();
        // A constrained model sends `{"action":..,"text":..}`; flatten it (and a
        // plain-string caller passes through) to the form the parser reads.
        let flat = todo_args_to_flat(args);
        let trimmed = flat.trim();
        let store = NotesStore::new();

        // No args → open notes panel
        if trimmed.is_empty() {
            return Ok(
                ActionResult::ok("__notes_panel__".to_string(), OutputType::Status)
                    .with_duration(start.elapsed().as_millis() as u64),
            );
        }

        let (cmd, rest) = trimmed.split_once(' ').unwrap_or((trimmed, ""));
        let rest = rest.trim();

        match cmd.to_lowercase().as_str() {
            "add" => {
                if rest.is_empty() {
                    return Ok(ActionResult::err("Usage: todo add <text>".to_string())
                        .with_duration(start.elapsed().as_millis() as u64));
                }
                let item = store.add_todo(&self.db, rest)?;
                Ok(ActionResult::ok(
                    format!("Added: {} ({})", item.text, item.id),
                    OutputType::Status,
                )
                .with_duration(start.elapsed().as_millis() as u64))
            }
            "list" | "ls" => {
                let todos = store.get_todos(&self.db)?;
                if todos.is_empty() {
                    return Ok(ActionResult::ok("No todos".to_string(), OutputType::Status)
                        .with_duration(start.elapsed().as_millis() as u64));
                }
                // `[x]`/`[ ]` was ASCII standing in for state a badge expresses
                // directly, and the id was shown only so it could be retyped
                // into `todo done <id>` — which is now the row's own action.
                let rows: Vec<Row> = todos
                    .iter()
                    .map(|t| {
                        let row = Row::new(&t.text)
                            // One id, not done/undone: the store verb is a
                            // TOGGLE, so inventing two action ids would imply a
                            // distinction the backend does not have. Only the
                            // label changes with current state.
                            .action(
                                "toggle",
                                if t.done { "Mark undone" } else { "Mark done" },
                                &t.id,
                                None,
                            )
                            .action("delete", "Delete", &t.id, Some(RiskLevel::Medium));
                        if t.done {
                            row.badge("done", BadgeTone::Ok)
                        } else {
                            row
                        }
                    })
                    .collect();
                Ok(ActionResult {
                    success: true,
                    output: Output::Rows {
                        sections: vec![Section {
                            title: Some(format!("Todos ({})", rows.len())),
                            rows,
                            handler: "todos".to_string(),
                        }],
                    },
                    duration_ms: start.elapsed().as_millis() as u64,
                    ..Default::default()
                })
            }
            "summary" => {
                let notes = store.get_notes(&self.db)?;
                let todos = store.get_todos(&self.db)?;

                let mut lines = Vec::new();

                // Notes section
                if !notes.is_empty() {
                    lines.push(format!("Notes ({}/{}):", notes.len(), MAX_NOTES));
                    for (i, n) in notes.iter().enumerate() {
                        let title = n.text.lines().next().unwrap_or(&n.text);
                        lines.push(format!("  {}. {}", i + 1, title));
                    }
                    lines.push(String::new());
                }

                // Todos section
                let pending: Vec<_> = todos.iter().filter(|t| !t.done).collect();
                let done: Vec<_> = todos.iter().filter(|t| t.done).collect();

                if !pending.is_empty() {
                    lines.push(format!("Pending ({}):", pending.len()));
                    for t in &pending {
                        lines.push(format!("  - {}", t.text));
                    }
                }

                if !done.is_empty() {
                    if !pending.is_empty() {
                        lines.push(String::new());
                    }
                    lines.push(format!("Done ({}):", done.len()));
                    for t in &done {
                        lines.push(format!("  - {}", t.text));
                    }
                }

                if lines.is_empty() {
                    lines.push("Nothing here — no notes and no todos.".to_string());
                }

                Ok(ActionResult::ok(lines.join("\n"), OutputType::Text)
                    .with_duration(start.elapsed().as_millis() as u64))
            }
            "done" | "check" | "toggle" => {
                if rest.is_empty() {
                    return Ok(ActionResult::err("Usage: todo done <id>".to_string())
                        .with_duration(start.elapsed().as_millis() as u64));
                }
                store.toggle_todo(&self.db, rest)?;
                Ok(
                    ActionResult::ok(format!("Toggled: {rest}"), OutputType::Status)
                        .with_duration(start.elapsed().as_millis() as u64),
                )
            }
            "delete" | "del" | "rm" | "remove" => {
                if rest.is_empty() {
                    return Ok(ActionResult::err("Usage: todo delete <id>".to_string())
                        .with_duration(start.elapsed().as_millis() as u64));
                }
                store.delete_todo(&self.db, rest)?;
                Ok(
                    ActionResult::ok(format!("Deleted: {rest}"), OutputType::Status)
                        .with_duration(start.elapsed().as_millis() as u64),
                )
            }
            // If the first word isn't a subcommand, treat the entire args as "add"
            _ => {
                let item = store.add_todo(&self.db, trimmed)?;
                Ok(ActionResult::ok(
                    format!("Added: {} ({})", item.text, item.id),
                    OutputType::Status,
                )
                .with_duration(start.elapsed().as_millis() as u64))
            }
        }
    }

    async fn completions(&self, partial: &str) -> Vec<CompletionItem> {
        let lower = partial.to_lowercase();
        TODO_SUBCOMMANDS
            .iter()
            .filter(|(cmd, _)| cmd.contains(&lower) || lower.is_empty())
            .map(|(cmd, desc)| CompletionItem {
                label: cmd.to_string(),
                icon_path: None,
                score: if cmd.starts_with(&lower) { 100 } else { 50 },
                description: Some(desc.to_string()),
                reason: None,
                thumb_b64: None,
                run: Some(format!("todo {cmd}")),
                ..Default::default()
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn note_title_never_panics_on_multibyte() {
        // 40th byte lands inside a multi-byte char — must not panic, must return
        // valid UTF-8 truncated before the char.
        let s = format!("{}最", "a".repeat(39)); // 39 ASCII + 3-byte char at 39..42
        let t = NotesHandler::note_title(&s);
        assert!(t.len() <= 40 && s.is_char_boundary(t.len()));
        // Emoji straddling the boundary.
        let e = format!("{}😀ok", "x".repeat(38));
        let t = NotesHandler::note_title(&e);
        assert!(t.chars().all(|c| c == 'x'));
        // First line only.
        assert_eq!(NotesHandler::note_title("hello\nworld"), "hello");
    }

    #[test]
    fn note_args_flatten_from_structured_json() {
        // A constrained model sends the typed object; it flattens to the string
        // the parser reads. Add renders WITH its verb (a multi-verb grammar
        // must); the parser strips it — see the drift test below.
        assert_eq!(
            note_args_to_flat(r#"{"action":"add","text":"buy milk"}"#),
            "add buy milk"
        );
        assert_eq!(note_args_to_flat(r#"{"action":"read"}"#), "read");
        let id = crate::db::new_id();
        assert_eq!(
            note_args_to_flat(&format!(r#"{{"action":"delete","id":"{id}"}}"#)),
            format!("delete {id}")
        );
        // A plain-string caller (human, legacy) passes straight through — bare
        // text still adds via the fallthrough.
        assert_eq!(note_args_to_flat("remember the milk"), "remember the milk");
        assert_eq!(note_args_to_flat("read"), "read");
        // Malformed JSON → raw fallback; the parser treats it like typed input.
        assert_eq!(note_args_to_flat("{not json"), "{not json");
    }

    /// Drift guard: every note verb's flat rendering must be accepted by the
    /// parser — end to end through `execute`, on a real (test) store.
    #[tokio::test]
    async fn note_grammar_flat_rendering_is_accepted_by_the_parser() {
        let db = crate::db::open_test_database();
        let handler = NotesHandler::new(db.clone());
        let ctx = crate::action_registry::ExecContext::default();

        // add: the rendered `add buy milk` must store "buy milk" (8 chars),
        // NOT "add buy milk" — this is what pins the verb-stripping parser.
        let r = handler
            .execute(&ctx, r#"{"action":"add","text":"buy milk"}"#)
            .await
            .unwrap();
        assert!(r.success);
        match &r.output {
            Output::Text { body, .. } => assert!(body.contains("(8 chars"), "{body}"),
            other => panic!("expected status text, got {other:?}"),
        }

        // read: lists the stored note under its title.
        let r = handler.execute(&ctx, r#"{"action":"read"}"#).await.unwrap();
        match &r.output {
            Output::Rows { sections } => {
                assert!(sections[0].rows.iter().any(|row| row.title == "buy milk"));
            }
            other => panic!("expected rows, got {other:?}"),
        }

        // delete: by the store-generated id.
        let store = NotesStore::new();
        let id = store.get_notes(&db).unwrap()[0].id.clone();
        let r = handler
            .execute(&ctx, &format!(r#"{{"action":"delete","id":"{id}"}}"#))
            .await
            .unwrap();
        assert!(r.success);
        assert!(store.get_notes(&db).unwrap().is_empty());

        // A note whose text merely CONTAINS "add" mid-sentence is untouched,
        // and bare text (the human path) still adds via the fallthrough.
        let r = handler
            .execute(&ctx, "remember to add flour")
            .await
            .unwrap();
        assert!(r.success);
        assert_eq!(
            store.get_notes(&db).unwrap()[0].text,
            "remember to add flour"
        );
    }

    #[test]
    fn todo_args_flatten_from_structured_json() {
        assert_eq!(
            todo_args_to_flat(r#"{"action":"add","text":"buy milk"}"#),
            "add buy milk"
        );
        assert_eq!(todo_args_to_flat(r#"{"action":"list"}"#), "list");
        assert_eq!(todo_args_to_flat(r#"{"action":"summary"}"#), "summary");
        let id = crate::db::new_id();
        assert_eq!(
            todo_args_to_flat(&format!(r#"{{"action":"done","id":"{id}"}}"#)),
            format!("done {id}")
        );
        // A verb missing its operand flattens to the bare verb, so the parser's
        // own usage error answers — not a junk item.
        assert_eq!(todo_args_to_flat(r#"{"action":"done"}"#), "done");
        assert_eq!(todo_args_to_flat(r#"{"action":"add","text":""}"#), "add");
        // A plain-string caller passes straight through.
        assert_eq!(todo_args_to_flat("add buy milk"), "add buy milk");
        // Malformed JSON → raw fallback.
        assert_eq!(todo_args_to_flat("{oops"), "{oops");
    }

    /// Drift guard: every todo verb's flat rendering must be accepted by the
    /// parser — end to end through `execute`, on a real (test) store.
    #[tokio::test]
    async fn todo_grammar_flat_rendering_is_accepted_by_the_parser() {
        let db = crate::db::open_test_database();
        let handler = TodoHandler::new(db.clone());
        let ctx = crate::action_registry::ExecContext::default();

        let r = handler
            .execute(&ctx, r#"{"action":"add","text":"buy milk"}"#)
            .await
            .unwrap();
        assert!(r.success);

        let store = NotesStore::new();
        let id = store.get_todos(&db).unwrap()[0].id.clone();
        assert_eq!(store.get_todos(&db).unwrap()[0].text, "buy milk");

        let r = handler
            .execute(&ctx, &format!(r#"{{"action":"done","id":"{id}"}}"#))
            .await
            .unwrap();
        assert!(r.success);
        assert!(store.get_todos(&db).unwrap()[0].done);

        for probe in [r#"{"action":"list"}"#, r#"{"action":"summary"}"#] {
            let r = handler.execute(&ctx, probe).await.unwrap();
            assert!(r.success, "{probe}");
        }

        let r = handler
            .execute(&ctx, &format!(r#"{{"action":"delete","id":"{id}"}}"#))
            .await
            .unwrap();
        assert!(r.success);
        assert!(store.get_todos(&db).unwrap().is_empty());
    }

    #[test]
    fn note_and_todo_schema_enums_match_the_grammar_verbs() {
        // The derived schemas' action enums must be exactly the grammars'
        // verbs — and those must stay the sets the parsers actually handle.
        let note_names: Vec<&str> = NOTE_GRAMMAR.verbs.iter().map(|v| v.name).collect();
        assert_eq!(note_names, vec!["add", "read", "delete"]);
        let todo_names: Vec<&str> = TODO_GRAMMAR.verbs.iter().map(|v| v.name).collect();
        assert_eq!(todo_names, vec!["add", "list", "done", "delete", "summary"]);
        for (schema, verbs) in [
            (NOTE_GRAMMAR.handler_schema(), note_names),
            (TODO_GRAMMAR.handler_schema(), todo_names),
        ] {
            let en = schema["properties"]["action"]["enum"].as_array().unwrap();
            assert_eq!(en.len(), verbs.len());
            for v in &verbs {
                assert!(en.iter().any(|e| e == v), "enum missing {v}");
            }
        }
    }

    mod row_actions {
        use super::super::{resolve_note_action, resolve_todo_action};

        /// A real store id, so the tests exercise the same shape production does.
        fn an_id() -> String {
            crate::db::new_id()
        }

        #[test]
        fn note_delete_resolves() {
            let id = an_id();
            assert_eq!(
                resolve_note_action("delete", &id).unwrap(),
                format!("note delete {id}")
            );
        }

        #[test]
        fn todo_toggle_maps_to_the_done_verb() {
            // The store operation is a toggle; `done` is the verb that performs
            // it. If this ever splits into two verbs, this test is the thing
            // that should fail.
            let id = an_id();
            assert_eq!(
                resolve_todo_action("toggle", &id).unwrap(),
                format!("todo done {id}")
            );
            assert_eq!(
                resolve_todo_action("delete", &id).unwrap(),
                format!("todo delete {id}")
            );
        }

        #[test]
        fn a_non_uuid_target_is_refused() {
            // Ids are store-generated UUIDs. Anything else did not come from a
            // row, so it must not reach a store lookup — this is what stops the
            // row-action channel being a way to name arbitrary strings.
            for bad in ["", "1", "../../x", "note delete x", "'; drop --"] {
                assert!(resolve_note_action("delete", bad).is_err(), "note: {bad}");
                assert!(resolve_todo_action("toggle", bad).is_err(), "todo: {bad}");
            }
        }

        #[test]
        fn unknown_action_ids_are_refused() {
            let id = an_id();
            assert!(resolve_note_action("toggle", &id).is_err());
            assert!(resolve_todo_action("archive", &id).is_err());
        }
    }
}
