pub mod byo;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::action_registry::RiskLevel;
use crate::error::LychiError;

/// The result of AI intent routing — a structured action.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiRoute {
    pub action_id: String,
    pub args: String,
}

/// A single step in an agent plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentStep {
    pub action_id: String,
    pub args: String,
    pub label: String,
    pub risk: RiskLevel,
}

/// A multi-step plan generated by AI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentPlan {
    pub id: String,
    pub input: String,
    pub steps: Vec<AgentStep>,
}

/// The AI can return either a single route or a multi-step plan.
#[derive(Debug, Clone)]
pub enum AiResponse {
    SingleRoute(AiRoute),
    Plan(AgentPlan),
}

/// Generate a short random plan ID.
pub fn generate_plan_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    format!("plan-{ts}")
}

/// Trait for AI providers (BYO, Ollama, Cloud).
///
/// Each provider implements the same interface so the router
/// can swap between them based on config.
#[async_trait]
pub trait AiProvider: Send + Sync {
    /// Parse natural language input into a structured command route (single-shot only).
    async fn route_intent(
        &self,
        input: &str,
        known_actions: &[&str],
    ) -> Result<AiRoute, LychiError>;

    /// Route input, returning either a single route or a multi-step plan.
    /// `context_hint` is an optional environment context string appended to the system prompt.
    async fn route_or_plan(
        &self,
        input: &str,
        known_actions: &[&str],
        context_hint: Option<&str>,
    ) -> Result<AiResponse, LychiError>;

    /// Check if the provider is reachable and functional.
    async fn health_check(&self) -> bool;

    /// Human-readable provider name (e.g. "anthropic", "openai", "ollama").
    fn name(&self) -> &str;

    /// Send a direct question to the AI with a custom system prompt.
    /// Used by the "ask" handler for QA rather than intent routing.
    async fn answer_question(
        &self,
        _system_prompt: &str,
        _question: &str,
    ) -> Result<String, LychiError> {
        Err(LychiError::Ai(
            "answer_question not supported by this provider".to_string(),
        ))
    }
}
