use serde::{Deserialize, Serialize};

use super::provider::AiRoute;

/// Risk level for an agent plan step.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Risk {
    Safe,
    Moderate,
    Dangerous,
}

/// A single step in an agent plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentStep {
    pub command: String,
    pub args: String,
    pub label: String,
    pub risk: Risk,
}

/// A multi-step plan generated by AI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentPlan {
    pub id: String,
    pub input: String,
    pub steps: Vec<AgentStep>,
}

/// The AI can return either a single route or a multi-step plan.
#[derive(Debug, Clone)]
pub enum AiResponse {
    SingleRoute(AiRoute),
    Plan(AgentPlan),
}

/// Generate a short random plan ID.
pub fn generate_plan_id() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    format!("plan-{ts}")
}

/// Dangerous shell patterns that override AI-assigned risk upward.
const DANGEROUS_PATTERNS: &[&str] = &[
    "rm ",
    "rm\t",
    "rmdir",
    "sudo ",
    "chmod ",
    "chown ",
    "mkfs",
    "dd ",
    "kill ",
    "pkill ",
    "shutdown",
    "reboot",
    "systemctl stop",
    "systemctl disable",
    " > ",
    " >> ",
    ">/",
    ">>/",
    "| xargs",
    "eval ",
    "exec ",
    ":(){ ",
    "fork",
];

/// Moderate shell patterns (file creation/modification).
const MODERATE_PATTERNS: &[&str] = &[
    "mkdir",
    "touch ",
    "cp ",
    "mv ",
    "cargo init",
    "cargo new",
    "npm init",
    "git init",
    "wget ",
    "curl ",
    "pip install",
    "npm install",
    "apt ",
    "dnf ",
    "pacman ",
];

/// Validate and potentially upgrade the risk level of a step.
/// Risk can only be upgraded, never downgraded.
pub fn validate_risk(step: &AgentStep) -> Risk {
    let args_lower = step.args.to_lowercase();

    // Check for dangerous patterns first
    for pat in DANGEROUS_PATTERNS {
        if args_lower.contains(pat) {
            return Risk::Dangerous;
        }
    }

    // Check for pipe or redirect operators (dangerous when combined with write)
    if args_lower.contains('|') || args_lower.contains('>') {
        return Risk::Dangerous;
    }

    // Check for moderate patterns
    if step.risk == Risk::Safe {
        for pat in MODERATE_PATTERNS {
            if args_lower.contains(pat) {
                return Risk::Moderate;
            }
        }
    }

    step.risk
}

#[cfg(test)]
mod tests {
    use super::*;

    fn step(args: &str, risk: Risk) -> AgentStep {
        AgentStep {
            command: "run".to_string(),
            args: args.to_string(),
            label: "test".to_string(),
            risk,
        }
    }

    #[test]
    fn safe_command_stays_safe() {
        assert_eq!(validate_risk(&step("ls -la", Risk::Safe)), Risk::Safe);
        assert_eq!(validate_risk(&step("code .", Risk::Safe)), Risk::Safe);
    }

    #[test]
    fn dangerous_patterns_override() {
        assert_eq!(
            validate_risk(&step("rm -rf /tmp/foo", Risk::Safe)),
            Risk::Dangerous
        );
        assert_eq!(
            validate_risk(&step("sudo apt update", Risk::Safe)),
            Risk::Dangerous
        );
    }

    #[test]
    fn pipe_is_dangerous() {
        assert_eq!(
            validate_risk(&step("cat file | grep foo", Risk::Safe)),
            Risk::Dangerous
        );
    }

    #[test]
    fn moderate_patterns_upgrade_safe() {
        assert_eq!(
            validate_risk(&step("cargo init my-project", Risk::Safe)),
            Risk::Moderate
        );
        assert_eq!(
            validate_risk(&step("mkdir new-dir", Risk::Safe)),
            Risk::Moderate
        );
    }

    #[test]
    fn moderate_stays_moderate() {
        assert_eq!(
            validate_risk(&step("cargo init my-project", Risk::Moderate)),
            Risk::Moderate
        );
    }

    #[test]
    fn never_downgrades() {
        assert_eq!(
            validate_risk(&step("ls -la", Risk::Dangerous)),
            Risk::Dangerous
        );
    }
}
