pub mod action_registry;
pub mod aliases;
pub mod clipboard;
pub mod config;
pub mod context;
pub mod db;
pub mod error;
pub mod executor;
pub mod history;
pub mod intent;
#[cfg(feature = "mpris")]
pub mod mpris;
pub mod notes;
pub mod paths;
pub mod providers;
pub mod reminders;
pub mod rules;
pub mod snippets;
